Host dev
	User uj
	HostName dev.ujjaval.dev
	ForwardAgent yes

Host sv
	User uj
	HostName sv.ujjaval.dev
	ForwardAgent yes

Host nuc
	User uj
	HostName nuc.ujjaval.dev
	ForwardAgent yes

Host synology
	User uj
	HostName drive.ujjaval.dev
